### ISSUE TITLE
Ability to show country code in form field

### ISSUE THREAD

**Issue by acenario** [SmileyChris/django-countries#125]
Hello,

Love the project. I understand it should be possible to do this on my own, but is there a way in which I could natively customize a country field to show just the country code or the country code and the country name?

Thanks,

Arjun

    country = LazyTypedChoiceField(choices=countries)

**Comment by SmileyChris** [comment]
Well if you just wanted the country codes, then you could just use `[(code, code) for code in countries.countries]`

Otherwise, subclass the `Countries` class and change the iter method to spit out what you want. The class could probably do with some method that abstracts the formatting of each choice, so if you wanted to work on that and do a pull request...
