### ISSUE TITLE
Adding UK to the list of countries gives a key error.

### ISSUE THREAD

**Issue by hossein761** [SmileyChris/django-countries#137]
only GB works it seems.

**Comment by SmileyChris** [comment]
Could you provide more information about which list of countries your adding `UK` to, and the full error traceback. Even better, provide a test ;)

**Comment by kremerben** [comment]
Is it possible to add 'UK' as an additional alias to 'GB'? If so what is the best/cleanest method to go about that. I'm not 100% clear on how/where to _add_ another country.

**Comment by SmileyChris** [comment]
I'm not quite sure what the benefit is of having an alias to an existing code. Usually you display the name rather than the code, and you could always just do something at the presentation layer to replace the representation of that code if you really needed to.

**Comment by kremerben** [comment]
The benefit in my mind was for running a django db query by a user typed country designation in a text search. Feedback I've received is some of our clients prefer to use UK vs GB, and I thought it may be easier to add UK as an alias to GB, rather than parse out _UK_ and swap it for _GB_ before running the query.

**Comment by SmileyChris** [comment]
Well setting up a new country is easy, see the readme. You could obviously
have aggregation issues, having two codes representing the same country
however...
