### ISSUE TITLE
Mention rename of Czech Republic to Czechia in changelog

### ISSUE THREAD

**Issue by saily** [SmileyChris/django-countries#171]
In Commit https://github.com/SmileyChris/django-countries/commit/183dc9f918e7757b48772cda4e48c25d37746393 the name of Czech Republic was changed to Czechia which [is the official name for Czechia since Oct. 2013](http://www.independent.co.uk/news/world/europe/whats-in-a-name-czech-republic-mulls-shock-rebranding-as-czechia-8874839.html). 

This should be mentioned in Changelog and added to a currently missing migration guide. People may run into unexpected issues when they were using `countries.by_name('Czech Republic')`, which will now returned an empty string `''`.

We should:

- Think about supporting both names, since in a lot of systems we may work with the old name still present.
- Think about raising an Exception if a countryname is not found/supported and/or not mentioned in `COUNTRIES_ONLY` settings variable.

**Comment by SmileyChris** [comment]
Thanks for the feedback

django-countries solely uses ISO 3166-1 names (only providing a common name when the official ISO name is obtuse). It's easier to stick with this than muddy the waters with arbitrary judgement calls. It would be nice if you could have multiple names for a single country code (maybe if the name is a list/tuple it gets expanded?) so that it was easier to let people support both names if they want to.
Open a new ticket for this functionality if you like.

I really think you're overstating the "a lot of systems" rely on country names. If anything, there should just be a warning for this method that official names change and not to rely on it without your own checking.
Raising an exception probably would have been a better option than returning an empty string, but changing that now would in itself be incompatible. Feel free to do a pull request which words a good warning in this method's docstring.

**Comment by saily** [comment]
@SmileyChris why did you close this ticket, nobody will work on this if you just close it.

**Comment by SmileyChris** [comment]
Closed since the core of this ticket is wontfix (not going to add ISO changes into the change log, not going to support non ISO names, not going to raise an exception for `by_name` because it'd be backwards incompatible)

There were valid issues that came out of this discussion though (and please know that I'm grateful you are contributing), so like I said:
> Open a new ticket for this functionality if you like.

and
> Feel free to do a pull request which words a good warning in this method's docstring.

**Comment by SmileyChris** [comment]
So it should be fully fixed now, anyway :+1: 

Thanks again @saily for bringing it up
