### ISSUE TITLE
country short name vs long name

### ISSUE THREAD

**Issue by radeksvarz** [SmileyChris/django-countries#217]
As discussed in #171 Czech Republic was renamed to Czechia. This is however correct only for some cases. As stated in official declaration of the ministry of foreign affairs ( http://www.mzv.cz/jnp/en/foreign_relations/public_diplomacy/digital_diplomacy/how_to_use_the_short_country_name.html ) Czechia is officially short name while Czech Republic stays as a long highly formal name.

This is reflected on the ISO page ( https://www.iso.org/obp/ui#iso:code:3166:CZ ):

> Alpha-2 code CZ
> Short name CZECHIA
> Short name lower case Czechia
> Full namethe Czech Republic
> Alpha-3 code CZE

Some countries have very similar shortname and full name ( https://www.iso.org/obp/ui#iso:code:3166:US ,  https://www.iso.org/obp/ui#iso:code:3166:GB ) so there the problem is not visible.

This creates the problem for applications which need to support situations like: 

> In which cases it is NECESSARY to use the FORMAL (political) country name? 

> •	Official government documents 
> •	International agreements and non-binding official documents such as MoUs
> •	Official top-level meetings of political representatives (table name cards in meeting rooms)

I believe the issue is valid for some other countries as well.

**Comment by SmileyChris** [comment]
I'm not sure what you see is the problem here. The country names can be overridden for a project, so if that's what an application needs then that's what can be done.

What's the summary of the issue you're trying to raise?

django-countries provides a list of the official ISO short names of every country. Is your suggestion to also provide the full name? If someone wants to write (and support) some scraping code to ensure the data can also stay up to date then I wouldn't be against it.

**Comment by radeksvarz** [comment]
> The country names can be overridden for a project, so if that's what an application needs then that's what can be done.

Ah, you are right. In that case I believe we can close the issue.

The other option would be to buy the ISO subscription for downloading of the whole csv file. Which can be done by the app devs as well (costs 300 CHF).

**Comment by SmileyChris** [comment]
Yeah, let's just close it for now. Thanks for the feedback though!
