### ISSUE TITLE
Searching by country name

### ISSUE THREAD

**Issue by predatorhmo** [SmileyChris/django-countries#242]
Hi,

I have next model:
```python
class SomeModel(models.Model):
    country = CountryField()
```

And next admin model:

```python
class SomeModelAdmin(admin.ModelAdmin):
    list_display = ('country',)
    search_fields = ('country',)
```

On admin page, when I try to search by country code(i.e. AU), it works well, but if I want to search by country name(i.e. Australia) no any result returns. Is it possible to make some workaround? 
![image](https://user-images.githubusercontent.com/4621172/48315850-33d98e00-e5e4-11e8-9ff0-3537bb67157e.png)

Thanks in advance.

**Comment by brandonrobertz** [comment]
Search by country name is super spotty. I've basically written my own replacement methods from common names to django_countries internal names. It would be nice if there was some kind of helper routine to do some of this. (E.g. "United States" fails because you need "United States of America" ... or "Democratic Republic of the Congo" when it needs to be Congo (Democratic Republic of the)")

**Comment by SmileyChris** [comment]
It also becomes more difficult taking into account internationalization. It's a solvable problem, but not one worth the time imo. Someone is welcome to have a crack at it though :)

**Comment by brandonrobertz** [comment]
That's fair. It's not really in the scope of the project and such things typically belong in a data normalization step.
