### ISSUE TITLE
Use Weblate for translations?

### ISSUE THREAD

**Issue by comradekingu** [SmileyChris/django-countries#269]
I found the Norwegian Bokmål list of languages is missing, and ended up here instead of finding myself able to do anything about it.

Comparing the two alternatives (from my experience of having used both extensively),

Transifex, other than being a bad tool, is closed source, spies on the user, no longer allows gratis hosting for libre software if it has any venue of commercialization, and has quite egregious terms and conditions. The last part is made worse by requiring an account to even see strings.

Weblate is a good tool, doesn't spy on the user, and allows gratis hosting for any libre software project. It allows anyone to make suggestions (without an account) and has GitHub integration. It has a cloud service on https://weblate.org/en/hosting/
Also, it has https://hosted.weblate.org/projects/iso-codes/iso-3166-1/ already, which could be used for mutual benefit, (with the translation memory) or possibly merged with the existing django-countries effort.

Hosted Weblate uses django-countries for the new website https://github.com/WeblateOrg/website/issues/91 :)

**Comment by SmileyChris** [comment]
Thanks for the suggestion, I did have a look at it back when this issue came through. It's just a case of churn work that I'm not interested in doing.

If someone wants to put in the work to make the django-countries deployment script that automatically updates from transifex work with weblate then I'd be more inclined.
