### ISSUE TITLE
Change the name Turkey to Turkiye

### ISSUE THREAD

**Issue by xi-business** [SmileyChris/django-countries#403]
Turkey changed its name to Turkiye this year. Its name in `COUNTRIES` should be updated, though probably Turkey should be put into `COMMON_NAMES` and/or `OLD_NAMES`.

Source: [Wikipedia article "Name of Turkey"](https://en.wikipedia.org/wiki/Name_of_Turkey)

**Comment by Mogost** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/721963/200003665-7cc9ba8a-73e8-4019-877b-3cd0e1d65482.png">

At first, I wanted to object because the Wikipedia article is called Turkey.  But then I did an additional check and according to the standard ISO-3166 the name was changed.

Since the library follows this standard, the decision to change the name seems logical. 
ISO link: https://www.iso.org/obp/ui#iso:code:3166:TR
https://github.com/SmileyChris/django-countries/blob/54c2fd3f9dd92e0868c5d7bf551479b9a90e4ae0/django_countries/data.py#L3-L15
