### ISSUE TITLE
Support for Python version 3.12 on PyPI

### ISSUE THREAD

**Issue by wrenmck** [SmileyChris/django-countries#442]
For Python 3.12 pkg_resources is no longer included by default.

I see in the changelog for the unreleased update 7.6 that the deprecated pkg_resources.iter_entry_points is replaced with importlib_metadata. Is it possible to get this update released on PyPI, please?

**Comment by jodal** [comment]
Installing django-countries 7.5.1 fails on Python 3.12 because the `pkg_resources` module is missing. At least when using Poetry there is no obvious way to install `setuptools` in a way such that it is available when Poetry installs `django-countries`.

@SmileyChris The fix in 22ec4fc03490a78581695c744ac4b91ae0ddae41 looks perfect, so all we need is a new release to PyPI. :pray:

**Comment by PetrDlouhy** [comment]
@SmileyChris +1 for the new release

**Comment by daphtdazz** [comment]
Hey @SmileyChris any idea when you might be able to get round to publishing a new release with this fix?

**Comment by MichaelGatesDev** [comment]
An issue more than 3 months old with a MR fix up for almost the same amount of time. 

It seems this project is stagnant and should either change maintainers or be marked as archived.

**Comment by SmileyChris** [comment]
This is fixed in the latest release.
