### ISSUE TITLE
ImportError: cannot import name CountryField

### ISSUE THREAD

**Issue by ChunAllen** [SmileyChris/django-countries#51]
I already installed Django Countries(pip install django_countries) and still I'm getting an error of ImportError: cannot import name CountryField. You can check this http://bpaste.net/show/324398/

**Comment by SiddhantTotade** [comment]
> I had same issue with a new install of `django_countries`
> 
> I had to do `from django_countries.fields import CountryField`

I am facing the same issue too...if you solve this problem please let me know

**Comment by SiddhantTotade** [comment]
> > I had same issue with a new install of `django_countries`
> > I had to do `from django_countries.fields import CountryField`
> 
> I am facing the same issue too...if you solve this problem please let me know

I resolved this error....solution ------>   just restart the django server and use it.. and if it is not working just write the following line ' from django_countries.fields import CountryField ' and use it in models but don't create model like ' models.CountryField() ' just write ' country = CountryField() ' and migrate it ....it will work for sure.

**Comment by anentropic** [comment]
even back in 2014 I wasn't such a n00b that I wouldn't realise the field had to be imported, and the readme at that time already showed the obvious usage:

```python
from django.db import models
from django_countries.fields import CountryField

class Person(models.Model):
    name = models.CharField(max_length=100)
    country = CountryField()
```

I can see a couple of clues what the issue was, for me at that time:

https://stackoverflow.com/questions/23973119/importerror-cannot-import-name-countryfield

https://github.com/SmileyChris/django-countries/commit/70b24e9223170735ddcfe2cbda0306752543016f

It seems like the readme (in Dec 2013...) used to advise `from django_countries import CountryField` 

Although the readme had been fixed by the time I commented in July 2014, I wonder if maybe it hadn't been published to PyPI or something and I was still looking at the old version.

Anyway, there is no issue any more, it's long ago fixed and published and the usage is obvious.
