### ISSUE TITLE
Add ability to query by country name

### ISSUE THREAD

**Issue by jschneier** [SmileyChris/django-countries#91]
It would be nice to be able to do this so I don't need to add yet another package to get that functionality. Is there any interest in a pull request with this functionality?

**Comment by SmileyChris** [comment]
So what is it that you want exactly - could you give a theoretical code example?

**Comment by jschneier** [comment]
``` python
countries.by_name('United States')
'US'
```

**Comment by SmileyChris** [comment]
Where is this country name coming from (I'm trying to understand the use case)? Do we need to match both common names and full ISO names? How do we handle i18n?

**Comment by jschneier** [comment]
I am grabbing it from Facebook via the ``user_location`` scoped permission. I agree that there are quite a few difficult questions. I have used [this](https://pypi.python.org/pypi/pycountry/) package in the past.

**Comment by SmileyChris** [comment]
Well `django_countries.data.COUNTRIES` is a standard dictionary that you could iterate and compare (as long as you explicit force 'en' translation).

I'm guessing that's what this theoretical `countries.by_name(country, translation='en')` could do.
Since this doesn't seem very intrusive, feel free to go ahead and attempt a pull request if it is of interest to you.

**Comment by jschneier** [comment]
Yes, I started to do that before I came here. Okay, thanks.

**Comment by SmileyChris** [comment]
How's progress?

**Comment by jschneier** [comment]
Hey, sorry for dropping the ball on this. I have reached the point where this would be useful to me so I'm going to give it a shot right now.
